version: '4'

services:
  app:
    container_name: api_node
    build: .
    ports: 
      - $PORT:$PORT
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "npx prisma migrate dev --name init && npm run dev"
    volumes:
      - .:/app

  postgres:
    container_name: pg_db
    image: postgres:latest
    ports:
      - $PGPORT:$PGPORT
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 50s
      timeout: 1000s
      retries: 10
      start_period: 1000s

